---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  #   - package-ecosystem: "devcontainers"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  #   - package-ecosystem: "docker"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  #   - package-ecosystem: "docker-compose"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
